version: "3"
services:
  team-capacity-frontend:
    image: nginx:1.17.6-alpine
    container_name: team-capacity-frontend
    networks:
      - webapp
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/app.conf:/etc/nginx/conf.d/app.conf

    labels:
        - traefik.backend=team-capacity-frontend
        - traefik.normal.frontend.rule=Host:dev.app.capa.team
        - traefik.docker-network=webapp
        - traefik.port=80
        - traefik.frontend.auth.basic=team-capa:$$2y$$05$$loseUPRLVb0qFa1K6zBhMeejWfd1y8SrkEeUqP4lzuPRhLjW7MFcy

networks:
  webapp:
    external: true
