export enum CreateProjectActionType {
  CREATE_PROJECT_HAS_ERRORED = "CREATE_PROJECT_HAS_ERRORED",
  CREATE_PROJECT_IS_LOADING = "CREATE_PROJECT_IS_LOADING",
  CREATE_PROJECT_HAS_SUCCESS = "CREATE_PROJECT_HAS_SUCCESS",
  PROJECT_PREFERENCE_FETCHED = "PROJECT_PREFERENCE_FETCHED",
  CLEAR_PROJECT = "CLEAR_PROJECT",
}

export enum CreateSprintActionType {
  CREATE_SPRINT_HAS_ERRORED = "CREATE_SPRINT_HAS_ERRORED",
  CREATE_SPRINT_IS_LOADING = "CREATE_SPRINT_IS_LOADING",
  CREATE_SPRINT_HAS_SUCCESS = "CREATE_SPRINT_HAS_SUCCESS",
  CLEAR_SPRINT = "CLEAR_SPRINT",
}

export enum ConfirmEmailActionType {
  CONFIRM_EMAIL_HAS_ERRORED = "CONFIRM_EMAIL_HAS_ERRORED",
  CONFIRM_EMAIL_IS_LOADING = "CONFIRM_EMAIL_IS_LOADING",
  CONFIRM_EMAIL_HAS_SUCCESS = "CONFIRM_EMAIL_HAS_SUCCESS",
}

export enum CreateProjectOnboardingActionType {
  CREATE_PROJECT_ONBOARDING_NEXT = "CREATE_PROJECT_ONBOARDING_NEXT",
  CREATE_PROJECT_ONBOARDING_PREV = "CREATE_PROJECT_ONBOARDING_PREV",
}

export enum GlobalErrorActionType {
  ERROR_WAS_THROWN = "ERROR_WAS_THROWN",
}

export enum LocaleActionType {
  UPDATE_LOCALE = "UPDATE_LOCALE",
}

export enum ProjectActionType {
  PROJECT_HAS_ERRORED = "PROJECT_GET_HAS_ERRORED",
  PROJECT_IS_LOADING = "PROJECT_IS_LOADING",
  PROJECT_HAS_SUCCESS = "PROJECT_HAS_SUCCESS",
  PROJECT_PREFERENCE_IS_LOADING = "PROJECT_PREFERENCE_IS_LOADING",
  PROJECT_PREFERENCE_FETCHED = "PROJECT_PREFERENCE_FETCHED",
}

export enum ProjectPreferenceActionType {
  PROJECT_PREFERENCE_HAS_ERRORED = "PROJECT_PREFERENCE_HAS_ERRORED",
  PROJECT_PREFERENCE_IS_LOADING = "PROJECT_PREFERENCE_IS_LOADING",
  PROJECT_PREFERENCE_UPDATE_SUCCESS = "PROJECT_PREFERENCE_UPDATE_SUCCESS",
}
