apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: capa-team-frontend
  namespace: ${K8S_NAMESPACE}

spec:
  # 1 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: capa-team-frontend
  template:
    metadata:
      labels:
        app: capa-team-frontend
    spec:
      containers:
        - name: capa-team-frontend
          env:
            - name: "NODE_ENV"
              value: "DEV"
          # Run this image
          image: eu.gcr.io/${PROJECT_NAME}/${IMAGE}:${CI_COMMIT_SHA}
          #command: ["tail", "-f"]
          # command: ["npm", "run", "app"]
          #command: ["node_modules/.bin/nodemon", "--delay=1000ms", "--exec", "node_modules/.bin/ts-node", "--watch", "app/**/*.ts", "index.ts"]
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
